name: PR Analyze CI
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-report:
    name: PR report
    runs-on: ubuntu-20.04
    if: "!contains(github.event.pull_request.title, '[hotfix]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Installing package
        run: yarn
      # check for typescript
      - name: Check Types
        run: yarn check:types
      # check for eslint
      - name: Lint
        run: yarn lint:fix
      # check for indentation
      - name: Prettier
        run: yarn prettier:check
      # check for build compilation
      - name: Build
        run: yarn build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          BUILD_NUMBER: ${{ github.run_number }}
