name: PR Title

on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: PR title lint
        uses: seferov/pr-lint-action@master
        with:
          title-regex: '\[(JIRA)-.*\]'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-close-message: 'Closing this pull request since the title does not contains the Task ID eg) feat-my-changes [JIRA-123]. Please fix the title and re-open the pull request.'
